name = "AffineMaps"
uuid = "2c83c9a8-abf5-4329-a0d7-deffaf474661"
version = "0.3.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ChangesOfVariables = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ChangesOfVariables = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0"
FlexiMaps = "6394faf6-06db-4fa8-b750-35ccc60383f7"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"

[extensions]
AffineMapsAdaptExt = "Adapt"
AffineMapsChangesOfVariablesExt = "ChangesOfVariables"
AffineMapsFlexiMapsExt = "FlexiMaps"
AffineMapsFunctorsExt = "Functors"
AffineMapsInverseFunctionsExt = "InverseFunctions"

[compat]
Adapt = "1, 2, 3, 4"
ChangesOfVariables = "0.1.3"
FlexiMaps = "0.1"
Functors = "0.2, 0.3, 0.4"
InverseFunctions = "0.1"
LinearAlgebra = "1"
julia = "1.6"

[extras]
FlexiMaps = "6394faf6-06db-4fa8-b750-35ccc60383f7"
